version: '3'

services:
  web:
    image: django-app
    container_name: django-container
    command: sh -c "python /mysite/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./mysite:/mysite  # Monta tu código local en el contenedor
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    networks:
      - django_network

  db:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_password
      POSTGRES_MAX_CONNECTIONS: 100
      POSTGRES_SHARED_BUFFERS: "256MB"
      POSTGRES_EFFECTIVE_CACHE_SIZE: "768MB"
      POSTGRES_MAINTENANCE_WORK_MEM: "64MB"
      POSTGRES_WAL_LEVEL: "replica"
      POSTGRES_CHECKPOINT_TIMEOUT: "10min"
      POSTGRES_CHECKPOINT_COMPLETION_TARGET: "0.9"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Cambia el puerto 5432 de tu máquina a 5433
    networks:
      - django_network

volumes:
  postgres_data:

networks:
  django_network:
    driver: bridge
